export const data = {
  products: [
    {
      // _id: "1",
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High quality shirt",
    },
    {
      // _id: "2",
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 9,
      description: "High quality product",
    },
    {
      // _id: "3",
      name: "Nike Slim Pants",
      slug: "nike-slim-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 14,
      brand: "Nike",
      rating: 4.2,
      numReviews: 14,
      description: "High quality pants",
    },
    {
      // _id: "4",
      name: "Adidas Fit Pants",
      slug: "adidas-fit-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 200,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.1,
      numReviews: 8,
      description: "High quality pants",
    },
  ],
};
